### ISSUE TITLE
glow.nvim is mangling file paths

### ISSUE THREAD

**Issue by snoblenet** [ellisonleao/glow.nvim#89]
Thanks for creating glow.nvim.

In one of my markdown files, I have a line like this:

```
  - [now](tasks/now.md)
```

In normal mode in Neovim, entering `gf` while the cursor is on the filepath takes me to the file.

In Glow in the CLI, this line is shown as:

```
  - [now](full/path/from/root/tasks/now.md)
```

Not perfect, but OK.

In glow.nvim, this line is shown as:

```
  - [now](/var/folders/ql/long-random-looking-string/T/shorter-random-looking-string/tasks/now.md)
```

This contradicts the goal of providing a pleasing markdown preview without distractions.

Is there a solution?

**Comment by ellisonleao** [comment]
hey, @snoblenet thanks for the PR. Unfortunately, I don't have an immediate solution for this but I already have something in mind that would help. That issue is because we use a strategy that can render current buffers without saving them first and also the ones which are. I've opened [a discussion](https://github.com/ellisonleao/glow.nvim/discussions/78) that will probably solve this issue too. Let me know if you have any thoughs
